# This is a basic workflow to help you get started with Actions

name: Sync Plugins

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency: main

jobs:
  deploy:
    name: Sync Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Generate PluginMaster
        run: python generate_pluginmaster.py

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Regenerate PluginMaster

      - name: Set URL
        run: sed -i 's|https://github.com/OkuKatsu/DalamudRepo/raw/master|https://${{ secrets.FTP_SERVER_URL }}|g' pluginmaster.json

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        continue-on-error: true
        with:
          SSH_PRIVATE_KEY: ${{ secrets.FTP_SERVER_PASSWD }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: /*
          REMOTE_HOST: ${{ secrets.FTP_SERVER_IP }}
          REMOTE_USER: ${{ secrets.FTP_SERVER_USERNAME }}
          TARGET: /www/wwwroot/${{ secrets.FTP_SERVER_URL }}/
          EXCLUDE: ".git*, .well-known/, .user.ini, .htaccess, .git/, .gitignore"
